version: '3.8'

services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8080"
    volumes:
      - ./service-discovery:/app
      - ~/.m2:/root/.m2
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8084:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8080/eureka
    volumes:
      - ./auth-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-discovery:8080/eureka
      - JWT_SECRET=UmaSenhaBemLongaParaNossaAplicacao
    volumes:
      - ./gateway-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
      - auth-service
    networks:
      - app-network

  ticket-service:
    build:
      context: ./ticket-service
    container_name: ticket-service
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=UmaSenhaBemLongaParaNossaAplicacao
    volumes:
      - ./ticket-service:/app
      - ~/.m2:/root/.m2
    depends_on:
      - service-discovery
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
